services:
  phpfpm:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
  nginx:
    image: nginx:1.26.0-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
volumes:
  db-store: